language: ruby
notifications:
  email: false
rvm:
  - 1.9.3
before_install:
  - npm install coffee-script
  # - "export DISPLAY=:99.0"
  # - "sh -e /etc/init.d/xvfb start"
  # - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
install:
  - sudo apt-get update
  - sudo apt-get install libqt4-dev qt4-qmake
before_script:
  - "sh compile.sh"
script: bundle exec jasmine-headless-webkit
