// Generated by CoffeeScript 1.3.3

/*

  expectBarcodeScan = (submit, expectedSerializedValue, inputTargetName, expectedInputValue, barcode, hitEnter = true)
*/


(function() {

  describe("Barcode Scanner", function() {
    it("is defined", function() {
      return expect(window.BarcodeScanner).toBeDefined();
    });
    it("puts a barcode scanner input to the last barcode-scanner-target", function() {
      loadFixtures('multiple-barcode-targets.html');
      return expectBarcodeScan(true, "first=&second=SPAPE", "second", "SPAPE", "SPAPE");
    });
    it("puts a barcode scanner input to a focused element first", function() {
      loadFixtures('multiple-barcode-targets.html');
      $("#jasmine-fixtures form:last input[name='first']").focus();
      return expectBarcodeScan(true, "first=SPAPE&second=", "first", "SPAPE", "SPAPE");
    });
    it("prevents submit when the specific data attribute is set on the form", function() {
      loadFixtures('form-with-prevent-submit.html');
      return expectBarcodeScan(false, null, "second", "SPAPE", "SPAPE");
    });
    return it("prevents submit when the specific data attribute is set on the input", function() {
      loadFixtures('input-with-prevent-submit.html');
      return expectBarcodeScan(false, null, "second", "SPAPE", "SPAPE");
    });
  });

}).call(this);
