// Generated by CoffeeScript 1.3.3
(function() {

  global.jQuery = require('jquery');

  global.$ = jQuery;

  global.window = require('jsdom').jsdom().createWindow();

  global.document = window.document;

  require('../../barcode-scanner.js');

  require('./helpers/key-event.js');

  describe("Barcode Scanner", function() {
    it("is defined", function() {
      return expect(window.BarcodeScanner).toBeDefined();
    });
    return it("listen for an input from a barcode scanner", function() {
      var form, input,
        _this = this;
      form = $("<form></form>");
      input = $("<input></input>");
      form.html(input);
      form.on("submit", function() {
        return console.log("SUBMIT");
      });
      KeyEvent.simulate('Z'.charCodeAt(0), 90);
      KeyEvent.simulate('Z'.charCodeAt(0), 90);
      return KeyEvent.simulate(13, 13);
    });
  });

}).call(this);
