// Generated by CoffeeScript 1.3.3
(function() {

  window.expectBarcodeScan = function(submit, expectedSerializedValue, inputTargetName, expectedInputValue, barcode, hitEnter) {
    var character, form, _i, _len, _ref;
    if (hitEnter == null) {
      hitEnter = true;
    }
    form = $("#jasmine-fixtures form:last");
    form.on("submit", function() {
      if (!submit) {
        return expect(true).toBe(false, "this barcode scan should not submit");
      }
    });
    _ref = barcode.split("");
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      character = _ref[_i];
      KeyEvent.simulate(character.charCodeAt(0));
    }
    if (hitEnter) {
      KeyEvent.simulate(13, 13);
    }
    expect(form.find("input[name='" + inputTargetName + "']").val()).toBe(expectedInputValue);
    if (expectedSerializedValue != null) {
      expect(form.serialize()).toBe(expectedSerializedValue);
    }
    return form.off("submit");
  };

}).call(this);
